// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQce9PR40vDxItWDpxB4btKB248a7b39U',
    appId: '1:868989986714:web:d0b3d6ba32ecf1b03b3c23',
    messagingSenderId: '868989986714',
    projectId: 'bakeryproject-6f924',
    authDomain: 'bakeryproject-6f924.firebaseapp.com',
    storageBucket: 'bakeryproject-6f924.appspot.com',
    measurementId: 'G-1VNP5SE2X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNK2kbMhAk43bds_W7_FnBaYqXp5E24zs',
    appId: '1:868989986714:android:b462ab3a47070c403b3c23',
    messagingSenderId: '868989986714',
    projectId: 'bakeryproject-6f924',
    storageBucket: 'bakeryproject-6f924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7nMKvS_moclW70SeWnHe3vMKO3g87n0',
    appId: '1:868989986714:ios:b8ef54220f7766583b3c23',
    messagingSenderId: '868989986714',
    projectId: 'bakeryproject-6f924',
    storageBucket: 'bakeryproject-6f924.appspot.com',
    iosClientId: '868989986714-impha18anbe95uligfsc3iv1ntcups0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.viuBakery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw7nMKvS_moclW70SeWnHe3vMKO3g87n0',
    appId: '1:868989986714:ios:b8ef54220f7766583b3c23',
    messagingSenderId: '868989986714',
    projectId: 'bakeryproject-6f924',
    storageBucket: 'bakeryproject-6f924.appspot.com',
    iosClientId: '868989986714-impha18anbe95uligfsc3iv1ntcups0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.viuBakery',
  );
}
